import { StyleSheet } from "@react-pdf/renderer";

export const pdfStyles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: "Helvetica",
    fontSize: 10,
    color: "#1f2937",
    backgroundColor: "#ffffff",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    paddingBottom: 15,
    marginBottom: 20,
  },
  logoSection: {
    flexDirection: "column",
  },
  logoText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#3b82f6",
  },
  companyDetails: {
    fontSize: 8,
    color: "#6b7280",
    marginTop: 4,
  },
  metaSection: {
    alignItems: "flex-end",
  },
  metaTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#111827",
  },
  metaText: {
    fontSize: 8,
    color: "#6b7280",
    marginTop: 2,
  },
  section: {
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#111827",
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
    paddingBottom: 4,
    marginBottom: 10,
    textTransform: "uppercase",
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 10,
  },
  gridCol6: {
    width: "50%",
    paddingRight: 10,
    marginBottom: 8,
  },
  gridCol4: {
    width: "33.33%",
    paddingRight: 10,
    marginBottom: 8,
  },
  label: {
    fontSize: 8,
    color: "#6b7280",
    textTransform: "uppercase",
    marginBottom: 2,
  },
  value: {
    fontSize: 10,
    fontWeight: "medium",
    color: "#111827",
  },
  scoreCard: {
    backgroundColor: "#f9fafb",
    borderWidth: 1,
    borderColor: "#f3f4f6",
    borderRadius: 8,
    padding: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 15,
  },
  scoreInfo: {
    flexDirection: "column",
    flex: 1,
  },
  scoreNumber: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#3b82f6",
  },
  table: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 4,
    overflow: "hidden",
    marginBottom: 15,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#f9fafb",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    padding: 6,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
    padding: 6,
  },
  tableCellLabel: {
    flex: 2,
    fontSize: 9,
    color: "#111827",
  },
  tableCellCond: {
    flex: 1,
    fontSize: 8,
    fontWeight: "bold",
  },
  tableCellNotes: {
    flex: 3,
    fontSize: 8,
    color: "#4b5563",
  },
  badgeExcellent: { color: "#10b981" },
  badgeGood: { color: "#059669" },
  badgeFair: { color: "#d97706" },
  badgePoor: { color: "#ea580c" },
  badgeCritical: { color: "#dc2626" },
  badgeNA: { color: "#9ca3af" },
  signatureSection: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 30,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    paddingTop: 15,
  },
  signatureBox: {
    width: "45%",
    alignItems: "center",
  },
  signatureText: {
    fontSize: 12,
    fontFamily: "Times-Italic",
    marginTop: 10,
    color: "#111827",
  },
});
